projects:
  appsync-3b77218:
    schemaPath: src/graphql/schema.json
    includes:
      - /graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: /graphql/API.ts
        docsFilePath: /graphql
        region: us-east-1
        apiId: tmdvqasujrcgvkgoazlbq65u54
        maxDepth: 4
extensions:
  amplify:
    version: 3
